CREATE TABLE "countries" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE "favorites" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "station_id" INTEGER NOT NULL REFERENCES "stations" ("id")
);

CREATE TABLE "genres" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE "stations" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "title" VARCHAR(100) NOT NULL,
    "description" TEXT,
    "country_id" INTEGER NOT NULL REFERENCES "countries" ("id"),
    "genre_id" INTEGER NOT NULL REFERENCES "genres" ("id")
);

CREATE TABLE "streams" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "station_id" INTEGER NOT NULL REFERENCES "stations" ("id"),
    "url" VARCHAR(255) NOT NULL
);
